### ISSUE TITLE
Forcing a subset of features to be part of the solution

### ISSUE THREAD

**Issue by ba3lwi** [bhklab/mRMRe#14]
Many application includes a prior knowledge of a set of features that must be part of the solution. Is there a way to modify mRMR to allow for that feature?

A possible way to do it is to calculate the pairwise correlation matrix as usual and then create another correlation matrix between the subset of features of interest and the rest of features. Then, we penalize all the features in the original correlation matrix by subtracting the average correlation of the subset of features of interest with each feature from the second correlation matrix.

**Comment by spapillon** [comment]
mRMRe does not support this application. In principle this would make a nice feature to add but unfortunately given our time constraints we don't see it implemented any time soon.
