### ISSUE TITLE
Crashing with feature_count > 0

### ISSUE THREAD

**Issue by bacalfa** [bhklab/mRMRe#19]
Whenever I try to call `mRMR.classic` or `mRMR.ensemble` with `feature_count` greater than 1, the R session crashes. I'm particularly testing an example with survival data.

**Comment by ChristopherEeles** [comment]
Hi @bacalfa,

The package has been updated since this issue was opened. If the issue persists with the latest release, please feel free to open a new issue.

Best,
Christopher Eeles
