### ISSUE TITLE
cannot install package: package does not exist in CRAN

### ISSUE THREAD

**Issue by amin0511** [bhklab/mRMRe#22]
I am having difficulty with installing your package. It has been deleted in CRAN. 

package ‘mRMRe’ is not available (for R version 3.4.3)

i tried installing it using "remotes" package, but again to no avail.

The downloaded binary packages are in
	C:\Users\aahmadi\AppData\Local\Temp\RtmpgXztq4\downloaded_packages
> library(remotes)
Warning message:
package ‘remotes’ was built under R version 3.4.4 
> install_github("cran/mRMRe")
Downloading GitHub repo cran/mRMRe@master
These packages have more recent versions available.
Which would you like to update?

1:   pkgconfig (2.0.1 -> 2.0.2) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
igraph    (NA    -> 1.2.2) [CRAN]
pkgconfig (2.0.1 -> 2.0.2) [CRAN]
Installing 2 packages: igraph, pkgconfig
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/igraph_1.2.2.zip'
Content type 'application/zip' length 8316376 bytes (7.9 MB)
downloaded 7.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pkgconfig_2.0.2.zip'
Content type 'application/zip' length 19967 bytes (19 KB)
downloaded 19 KB

package ‘igraph’ successfully unpacked and MD5 sums checked
package ‘pkgconfig’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\aahmadi\AppData\Local\Temp\RtmpgXztq4\downloaded_packages
Running `R CMD build`...
* checking for file 'C:\Users\aahmadi\AppData\Local\Temp\RtmpgXztq4\remotes14f0569f70fa\cran-mRMRe-9f13944/DESCRIPTION' ... OK
* preparing 'mRMRe':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking vignette meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'mRMRe_2.0.7.tar.gz'
* installing *source* package 'mRMRe' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mRMRe.dll" OBJECTS="Data.o Filter.o Math.o Matrix.o MutualInformationMatrix.o exports.o"' had status 127
ERROR: compilation failed for package 'mRMRe'
* removing 'C:/Program Files/R/R-3.4.3/library/mRMRe'
In R CMD INSTALL
Error: (converted from warning) running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.4.3\library" "C:/Users/aahmadi/AppData/Local/Temp/RtmpgXztq4/file14f042e12d98/mRMRe_2.0.7.tar.gz"' had status 1
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
3: In missing_devel_warning(pkgdir) :
  Package mRMRe has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
> library(mRMRe)
Error in library(mRMRe) : there is no package called ‘mRMRe’
> install.packages("mRMRe")
Warning in install.packages :
  package ‘mRMRe’ is not available (for R version 3.4.3)

I found the most recent version and unzipped it and copied the folder in my 
C:\Program Files\R\R-3.4.3\library\mRMRe
but i got the message that it was not installed properly.

**Comment by ChristopherEeles** [comment]
I am not sure if this was relevant at the time this issue was opened, but the R core team changed the default serialization method for R objects (.rds, .rda, .RData, etc.) in R >= 3.5. As a result this package now requires R >= 3.5 to be installed.

Please feel free to open a new issue if this does not resolve the problem.

Best,
Christopher Eeles
