### ISSUE TITLE
The return variables contain the response variable

### ISSUE THREAD

**Issue by hope-data-science** [bhklab/mRMRe#25]
I am a user of your package and recently find that when I increase the ensemble number (e.g. solution count), some of the selected variables include the response varible, which is undesirable. Is there a way to fix it?

**Comment by clareli9** [comment]
Hi. Thank you for letting us know about the issues. May I know which method you use to generate the solutions, exhaustive or bootstrap?

**Comment by hope-data-science** [comment]
I used the default method provided by the vignette (but increase the solution count), which is:
```
> mRMR.ensemble(data = dd, target_indices = c(1),
 + solution_count = 5, feature_count = 30)
```
Thank you.

**Comment by ChristopherEeles** [comment]
We have pushed a change to the master branch and will be submitting the update to CRAN later today. If you have further issues with the package please on another issue and we would be happy to help resolve it.
