### ISSUE TITLE
Does mRMRe support unordered factor?

### ISSUE THREAD

**Issue by ahmed-Q4** [bhklab/mRMRe#5]
Hello,

I was wondering if the algorithm in mRMRe are designed to handle un-ordered factor variable in the data set?

Thank you

**Comment by bhaibeka** [comment]
It does not.

**Comment by ahmed-Q4** [comment]
Thanks for the quick reply.

**Comment by huangmozhilv** [comment]
What if the binary factor is formatted as ordered 0/1 factor?

**Comment by spapillon** [comment]
This application would indeed work.
