### ISSUE TITLE
how to control bootstrap subsample size?

### ISSUE THREAD

**Issue by thomasmooon** [bhklab/mRMRe#9]
Hello.
I'm using this efficient MRMR implementation for feature selection of feature matrices with dimension e. g. 50K x 5K (nSamples x nFeatures). If using  `method = "bootstrap"`, how can I control the bootstrap samplesize, e. g. to take only a subset of 10% of the original data during ensemble feature selection?

The pdf contained in the [supplemental information](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/29/18/10.1093_bioinformatics_btt383/2/btt383_Supplementary_Data.zip?Expires=1507915639&Signature=DvCtO2jLM1bGyGsoj6XdAiqOE0n8csyyx5qqTC~tETvlRbxMeKAyrEKM2vsaQ3yjLawR-9NE~Ym~ra0qhs2Di8Rs29i~-0aQD98YY6YmzUdoQwewZZukLzGb7Sij52ilzEomETNV~-P2itonpfvCQEnkd7r7q34mSHaR8s5k67CULVqwvs1kXQS2w1bFiAZG3VzLv-or2Kpt57MsSzjkrhgr1N2xEZg7RnHB0IVpQpPABL~tHB6g4TC-LvEg75ywbyfAoz7ZhZ2CbC5uISKFm~PjIxChRLIq6UIKeYxLJYJq3sFZbcy7x7y56~shaF3ZSq9L~OUI1h9Ko-8WdZkbTw__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q) prescribes the parameter `m`, introduced in section "Algorithm 2", but I can't find a corresponding variable in the methods. 

![image](https://user-images.githubusercontent.com/29228225/31507877-85464502-af7c-11e7-9766-30571b7013b9.png)

**Comment by thomasmooon** [comment]
@bhaibeka any ideas?

**Comment by bhaibeka** [comment]
Bootstrap by definition keeps on average 67% of unique samples in the training set. This is not something you can currently set as a parameter. We have no plan to update the code to include it but if you do, we would be happy to integrate it in the master branch of the package.

**Comment by thomasmooon** [comment]
Thanks for the info. Unfortunately I don't have the C++ skills to do that.
